//PRODUCAO DE RECURSOS
export const PROD_DE_RECURSOS = 1111; //Recursos por hora

//PRODUCAO DE FAVORES
export const PRODUCAO_BASE_FAVOR = 1; // Favor por hora

//TEMPO DE CONSTRUCAO DE EDIFICIOS E TREINAMENTO DE UNIDADES
export const TEMPO_CONSTRUCAO_EDIFICIOS = 11;
export const TEMPO_TREINAMENTO_UNIDADES = 1;

//TAMANHO MAXIMO DE FILA DE OBRAS E RECRUTAMENTO
export const TAMANHO_MAXIMO_FILA_OBRAS = 7;
export const TAMANHO_MAXIMO_FILA_RECRUTAMENTO = 3;



