export const EDIFICIOS = {
  'senado': {
    id: 'senado',
    nome: 'Senado',
    descricao: 'O centro político da sua cidade. Aumenta a velocidade de construção.',
    imagem: '/edificios/senado.png',
    custoBase: { madeira: 100, pedra: 80, prata: 50 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 120,
    custoPop: 2,
    nivelMaximo: 15
  },
  'serraria': {
    id: 'serraria',
    nome: 'Serraria',
    descricao: 'Produz madeira bruta para construções e tropas.',
    imagem: '/edificios/madeireira.png',
    custoBase: { madeira: 50, pedra: 30, prata: 20 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 60,
    multiplicadorProducao: 10,
    custoPop: 1,
    nivelMaximo: 40
  },
  'pedreira': {
    id: 'pedreira',
    nome: 'Pedreira',
    descricao: 'Fornece pedras para muralhas e edifícios.',
    imagem: '/edificios/pedreira.png',
    custoBase: { madeira: 30, pedra: 50, prata: 20 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 60,
    multiplicadorProducao: 10,
    custoPop: 1,
    nivelMaximo: 40
  },
  'mina-de-prata': {
    id: 'mina-de-prata',
    nome: 'Mina de Prata',
    descricao: 'Extrai minério de prata para comércio e divindades.',
    imagem: '/edificios/mina_prata.png',
    custoBase: { madeira: 40, pedra: 40, prata: 50 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 60,
    multiplicadorProducao: 10,
    custoPop: 1,
    nivelMaximo: 40
  },
  'fazenda': {
    id: 'fazenda',
    nome: 'Fazenda',
    descricao: 'Fornece alimento para seus cidadãos e exército. Aumenta a população máxima.',
    imagem: '/edificios/fazenda.png',
    custoBase: { madeira: 40, pedra: 20, prata: 20 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 60,
    custoPop: 0,
    nivelMaximo: 45
  },
  'armazem': {
    id: 'armazem',
    nome: 'Armazém',
    descricao: 'Local onde as matérias-primas são armazenadas. Aumenta a capacidade de recursos.',
    imagem: '/edificios/armazem.png',
    custoBase: { madeira: 50, pedra: 50, prata: 20 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 60,
    custoPop: 1,
    nivelMaximo: 35
  },
  'quartel': {
    id: 'quartel',
    nome: 'Quartel',
    descricao: 'No quartel, você pode recrutar tanto tropas regulares, como unidades míticas. Quanto maior o nível do quartel, mais rápido será treinado as suas tropas.',
    imagem: '/edificios/quartel.png',
    custoBase: { madeira: 150, pedra: 120, prata: 80 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 300,
    custoPop: 3,
    nivelMaximo: 30,
    requisitos: { 'senado': 4, 'mina-de-prata': 1 }
  },
  'templo': {
    id: 'templo',
    nome: 'Templo',
    descricao: 'Local de culto aos Deuses. Aumenta a produção de favores divinos.',
    imagem: '/edificios/templo.png',
    custoBase: { madeira: 120, pedra: 120, prata: 120 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 600,
    custoPop: 2,
    nivelMaximo: 30,
    requisitos: { 'senado': 15, 'pedreira': 12, 'muralha': 6 }
  },
  'mercado': {
    id: 'mercado',
    nome: 'Mercado',
    descricao: 'Permite trocar recursos com outras cidades ou aldeias bárbaras.',
    imagem: '/edificios/mercado.png',
    custoBase: { madeira: 80, pedra: 80, prata: 80 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 240,
    custoPop: 2,
    nivelMaximo: 30,
    requisitos: { 'senado': 5, 'armazem': 5 }
  },
  'porto': {
    id: 'porto',
    nome: 'Porto',
    descricao: 'Permite a construção de navios e barcos de transporte.',
    imagem: '/edificios/porto.png',
    custoBase: { madeira: 200, pedra: 100, prata: 150 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 480,
    custoPop: 5,
    nivelMaximo: 30,
    requisitos: { 'senado': 14, 'serraria': 15, 'pedreira': 10, 'mina-de-prata': 10 }
  },
  'academia': {
    id: 'academia',
    nome: 'Academia',
    descricao: 'Onde novas tecnologias e unidades de elite são pesquisadas.',
    imagem: '/edificios/senado.png',
    custoBase: { madeira: 150, pedra: 150, prata: 150 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 900,
    custoPop: 3,
    nivelMaximo: 36,
    requisitos: { 'senado': 8, 'fazenda': 6, 'quartel': 5 }
  },
  'muralha': {
    id: 'muralha',
    nome: 'Muralha',
    descricao: 'Protege a cidade contra-ataques terrestres.',
    imagem: '/edificios/pedreira.png',
    custoBase: { madeira: 50, pedra: 150, prata: 50 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 60,
    custoPop: 0,
    nivelMaximo: 25,
    requisitos: { 'senado': 5, 'pedreira': 3 }
  },
  'gruta': {
    id: 'gruta',
    nome: 'Gruta',
    descricao: 'Permite armazenar prata para espionagem e proteção contra espiões.',
    imagem: '/edificios/mina_prata.png',
    custoBase: { madeira: 50, pedra: 50, prata: 200 },
    multiplicadorCusto: 1.15,
    multiplicadorTempo: 1.15,
    tempoBase: 180,
    custoPop: 1,
    nivelMaximo: 10,
    requisitos: { 'senado': 10, 'armazem': 4, 'mercado': 4 }
  }
} as const;

export type IdEdificio = keyof typeof EDIFICIOS;
